[profile.default]
libs = ['lib']
out = 'out'
src = 'contracts'
test = 'forge-test'
script = 'scripts'
gas_reports_ignore = [
    "JBTokenStore",
    "JBSplitsStore",
    "JBSingleTokenPaymentTerminalStore",
    "JBProjects",
    "JBFundingCycleStore",
    "JBETHPaymentTerminal",
    "JBDirectory",
    "JBController",
    "AccessJBLib",
    "JBIpfsDecoder",
    "ForTest_JBTiered721Delegate",
    "ForTest_JBTiered721DelegateStore",
    "JBTiered721DelegateStore",
]

optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
